version: '3.8'


services:
  db: # Serviço do PostgreSQL
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: user             
      POSTGRES_PASSWORD: password       
      POSTGRES_DB: financial_system    
    ports:
      - "5432:5432"                    
    volumes:
      - pgdata:/var/lib/postgresql/data 

  pgadmin: 
    image: dpage/pgadmin4:latest       
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com  #
      PGADMIN_DEFAULT_PASSWORD: admin        
    ports:
      - "5050:80"                             
    depends_on:
      - db                                    
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs_app
    ports:
      - "3000:3000"                   
    volumes:
      - .:/app                         
      - /app/node_modules              
    environment:
      POSTGRES_HOST: db                 
      POSTGRES_PORT: 5432              
      POSTGRES_USER: user              
      POSTGRES_PASSWORD: password      
      POSTGRES_DB: financial_system    
    depends_on:
      - db                              

volumes:
  pgdata:                               
